# -*- coding: utf-8 -*-
"""ML Project 3 Models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4T9abuvwsDNvMaXhmqsRwPcotJ8oHpx
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

# Removed %%writefile app.py
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb

# ----------------------------
# 🌈 Zomato Theme & Page Setup
# ----------------------------
st.set_page_config(page_title="Zomato Delivery Time Predictor", layout="wide") # Using layout wide for better use of space
st.markdown("""
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Times+New+Roman&display=swap');
        html, body, [class*="st-"] {{
            font-family: 'Times New Roman', serif !important;
            color: white; /* Ensure default text color is white */
        }}
        /* Apply red background to the main content area and the entire app */
        .stApp {{
            background-color: #A8232C; /* Zomato Dark Red */
            color: white;
        }}
        .stSidebar {{
            background-color: white !important; /* White background for sidebar */
            color: #A8232C !important; /* Dark Red text for sidebar */
        }}
        .stSelectbox label, .stNumberInput label, .stButton>button {{
            color: white !important; /* Labels and button text in white */
            font-size: 18px;
        }}
         .stSelectbox div[data-baseweb="select"] > div {{
            color: #cb202d !important; /* Selected item in selectbox */
        }}
         .stTextInput>div>div>input {{
            color: white !important; /* Input text in white */
         }}
        .prediction-card {{
            background-color: white;
            color: #A8232C !important; /* Prediction card text in Zomato Dark Red */
            border-radius: 15px;
            padding: 20px;
            text-align: center;
            font-size: 20px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.3);
            margin-bottom: 20px; /* Add some space below cards */
        }}

        /* Ensure text within prediction cards is Zomato Dark Red */
        .prediction-card b, .prediction-card {{
            color: #A8232C !important;
        }}

        h1, h2, h3, h4, h5, h6 {{
            text-align: center;
            font-family: 'Times New Roman', serif !important;
            color: white !important; /* Headings in white */
        }}
        /* Ensure text elements in the main content area are white */
        .main .block-container, .css-j080pf, .css-10trgqc, .stMarkdown p {{
            color: white !important;
        }}
    </style>
""", unsafe_allow_html=True)

# ----------------------------
# 🚴‍♂️ Title
# ----------------------------
st.markdown("<h1>🚴‍♂️ Zomato Delivery Time Predictor</h1>", unsafe_allow_html=True)
st.markdown("<h3>Predict your delivery time using three powerful ML models — fast, fresh, and on time!</h3>", unsafe_allow_html=True)

# ----------------------------
# 📦 Load Dataset (for determining input ranges)
# ----------------------------
try:
    data = pd.read_csv("Zomato Delivery Prediction.csv")
    data = data.rename(columns={
        'Distance_km': 'Distance_Km',
        'Rider_Experience_years': 'Rider_Experience',
        'Delivery_Time_min': 'Delivery_Time'
    })

    # Determine min/max for input fields
    min_distance = float(data['Distance_Km'].min())
    max_distance = float(data['Distance_Km'].max())
    min_rider_exp = float(data['Rider_Experience'].min())
    max_rider_exp = float(data['Rider_Experience'].max())

    # Get unique values for categorical features from the dataset
    traffic_options = data['Traffic'].unique().tolist()
    weather_options = data['Weather'].unique().tolist()
    time_of_day_options = data['Time_of_Day'].unique().tolist()
    restaurant_popularity_options = data['Restaurant_Popularity'].unique().tolist()
    vehicle_type_options = data['Vehicle_Type'].unique().tolist()


    # Drop unnecessary columns after determining ranges and unique values
    cols_to_use = ['Distance_Km', 'Traffic', 'Weather', 'Time_of_Day',
                   'Restaurant_Popularity', 'Vehicle_Type', 'Rider_Experience', 'Delivery_Time']
    data = data[cols_to_use]

    # Encode categorical columns
    categorical_cols = ['Traffic', 'Weather', 'Time_of_Day', 'Restaurant_Popularity', 'Vehicle_Type']
    x = data.drop('Delivery_Time', axis=1)
    y = data['Delivery_Time']
    x_encoded = pd.get_dummies(x, columns=categorical_cols, drop_first=True)

    x_train, x_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=42)

    # ----------------------------
    # 🧠 Train Models
    # ----------------------------
    lin_model = LinearRegression().fit(x_train, y_train)
    rf_model = RandomForestRegressor(n_estimators=100, random_state=42).fit(x_train, y_train)
    # For XGBoost, train on the encoded training data
    xgb_model = xgb.XGBRegressor(objective='reg:squarederror', eval_metric='rmse', max_depth=3, n_estimators=50, random_state=42)
    xgb_model.fit(x_train, y_train)


    data_loaded_and_models_trained = True

except FileNotFoundError:
    st.error("Error: 'Zomato Delivery Prediction.csv' not found. Please make sure the file is in the correct directory.")
    data_loaded_and_models_trained = False
except Exception as e:
    st.error(f"An error occurred during data loading or model training: {e}")
    data_loaded_and_models_trained = False


# ----------------------------
# 🧾 User Inputs
# ----------------------------
st.subheader("📥 Enter Delivery Details")
col1, col2 = st.columns(2)

if data_loaded_and_models_trained:
    with col1:
        distance = st.number_input("Distance (in km)", min_value=min_distance, max_value=max_distance, value=min_distance + (max_distance - min_distance)/2.0, step=0.1)
        traffic = st.selectbox("Traffic", traffic_options)
        weather = st.selectbox("Weather", weather_options)
        time_of_day = st.selectbox("Time of Day", time_of_day_options)
    with col2:
        restaurant_popularity = st.selectbox("Restaurant Popularity", restaurant_popularity_options)
        vehicle_type = st.selectbox("Vehicle Type", vehicle_type_options)
        rider_exp = st.number_input("Rider Experience (Years)", min_value=min_rider_exp, max_value=max_rider_exp, value=min_rider_exp + (max_rider_exp - min_rider_exp)/2.0, step=0.1)

    # ----------------------------
    # 🔍 Prepare Input for Prediction
    # ----------------------------
    input_dict = {
        'Distance_Km': [distance],
        'Rider_Experience': [rider_exp],
        'Traffic': [traffic],
        'Weather': [weather],
        'Time_of_Day': [time_of_day],
        'Restaurant_Popularity': [restaurant_popularity],
        'Vehicle_Type': [vehicle_type]
    }
    input_df = pd.DataFrame(input_dict)
    input_encoded = pd.get_dummies(input_df, columns=categorical_cols, drop_first=True)

    # Ensure all columns from training data are present in input data
    for col in x_encoded.columns:
        if col not in input_encoded.columns:
            input_encoded[col] = 0

    # Align input with training data columns order
    input_encoded = input_encoded[x_encoded.columns]


    # ----------------------------
    # 🎯 Predict
    # ----------------------------
    if st.button("Predict Delivery Time"):
        lin_pred = lin_model.predict(input_encoded)[0]
        rf_pred = rf_model.predict(input_encoded)[0]
        xgb_pred = xgb_model.predict(input_encoded)[0]


        st.markdown("<h2>🕒 Predicted Delivery Times</h2>", unsafe_allow_html=True)
        col1, col2, col3 = st.columns(3)

        with col1:
            st.markdown(f"<div class='prediction-card'><b>Linear Regression</b><br>{lin_pred:.2f} minutes</div>", unsafe_allow_html=True)
        with col2:
            st.markdown(f"<div class='prediction-card'><b>Random Forest</b><br>{rf_pred:.2f} minutes</div>", unsafe_allow_html=True)
        with col3:
            st.markdown(f"<div class='prediction-card'><b>XGBoost</b><br>{xgb_pred:.2f} minutes</div>", unsafe_allow_html=True)